project_name: rurl

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/jmylchreest/rurl/internal/config.Version={{.Version}}
      - -X github.com/jmylchreest/rurl/internal/config.Commit={{.Commit}}
      - -X github.com/jmylchreest/rurl/internal/config.Date={{.Date}}
    flags:
      - -trimpath

archives:
  - format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: 'Maintenance'
      regexp: "^.*?(build|chore|ci|refactor|style|perf|test)[(\\w)]*:+.*$"
      order: 2
  filters:
    exclude:
      - '^docs?:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - '^style:'
      - '^Merge pull request'
      - '^Merge branch'
      - '^Merge remote-tracking'
      - '^Merge tag'
      - '^Release '
      - '^WIP:'
      - '^wip:'
      - '^\[skip ci\]'
      - '(?i)^typo'

release:
  prerelease: auto
  footer: |
    ## Status
    [![Release](https://github.com/jmylchreest/rurl/actions/workflows/release.yml/badge.svg)](https://github.com/jmylchreest/rurl/actions/workflows/release.yml) 